version: '3.7'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - polls_pg_data:/var/lib/postgresql/data 
    ports:
      - 5432:5432
 
volumes:
  polls_pg_data: